"""Acceptance: pytest failing-test census (debt 74db82e027; pytest/v2
formats per docs/EDC.md §12).

The measured spec3 failure: a digest naming ONE failure where the task
needed all 8 made haiku re-run the suite eight times with slicers. The
census enumerates every failing test — node id, source location, failure
class, one-line summary (v2 hierarchy levels 3-4, on by default), stdout
coordinates, region span over its traceback block — and outranks the
inline first-failure detail when budget is tight. When even the identity
census cannot fit, the render escalates to FLOOD (declared omissions +
content-addressed full-census blob) — identities are never silently cut.
Fixtures are REAL pytest output, generated by subprocess pytest over
seeded failing test files, covering -q, -v, and pipe-truncated shapes.
"""

import os
import re
import subprocess
import sys
import textwrap

import pytest
from conftest import make_store, make_ws

SEED = textwrap.dedent('''\
    class TestBox:
        def test_edge(self):
            box = {"lo": 1, "hi": 0}
            assert box["lo"] <= box["hi"]

    def test_alpha():
        assert 2 + 2 == 5

    def test_beta():
        raise ValueError("beta exploded")

    def test_gamma():
        assert "needle" in "haystack"

    def test_delta():
        assert [1, 2] == [1, 3]

    def test_epsilon():
        x = None
        assert x is not None

    def test_zeta():
        assert 10 / 3 > 4

    def test_eta():
        d = {}
        assert d["missing"] == 1

    def test_ok():
        assert True
''')

PASS_SEED = textwrap.dedent('''\
    def test_one():
        assert 1 + 1 == 2

    def test_two():
        assert "a" in "abc"

    def test_three():
        assert sorted([2, 1]) == [1, 2]
''')

FAIL_IDS = [
    "test_seed.py::TestBox::test_edge",
    "test_seed.py::test_alpha",
    "test_seed.py::test_beta",
    "test_seed.py::test_gamma",
    "test_seed.py::test_delta",
    "test_seed.py::test_epsilon",
    "test_seed.py::test_zeta",
    "test_seed.py::test_eta",
]

# pytest/v2 census row: numbered, id + location · class [· one-liner] ·
# stdout coordinates [· span] (EDC §12.2; addresses are contract-driven).
CENSUS_ROW_RE = re.compile(
    r"^\s+\d+\. (\S+)  (\S+) · (\S+)(?: · .*?)? · stdout:L(\d+)(?:-L(\d+))?"
    r"(?: · span ([0-9a-f]{10}))?$",
    re.M,
)


@pytest.fixture(scope="module")
def real_outputs(tmp_path_factory):
    """Real pytest output in the shapes the profile must survive."""
    seed = tmp_path_factory.mktemp("pytest-seed")
    (seed / "test_seed.py").write_text(SEED, encoding="utf-8")
    (seed / "test_pass.py").write_text(PASS_SEED, encoding="utf-8")
    env = {**os.environ}
    env.pop("PYTEST_ADDOPTS", None)

    def run(*args):
        proc = subprocess.run(
            [sys.executable, "-m", "pytest", "-p", "no:cacheprovider", *args],
            cwd=seed, env=env, capture_output=True, text=True, timeout=120,
        )
        return proc.stdout

    return {
        "fail_q": run("test_seed.py", "-q"),
        "fail_v": run("test_seed.py", "-v"),
        "pass_default": run("test_pass.py"),
    }


def _ctx_for(tmp_path, text, *, result_tokens=1200, argv=("pytest", "-q"), dense=False):
    from ctx.digest.base import DigestContext, StreamView
    from ctx.workspace import resolve_workspace

    (tmp_path / "ctx.toml").write_text(
        f"version = 1\n[budgets]\nresult_tokens = {result_tokens}\n", encoding="utf-8"
    )
    ws = resolve_workspace(str(tmp_path))
    out = StreamView("stdout", len(text.encode()), len(text.splitlines()), "text/plain", text, True)
    err = StreamView("stderr", 0, 0, "text/plain", "", True)
    manifest = {
        "argv": list(argv), "cwd": ".", "shell": False,
        "result": {"exitCode": 1, "signal": None, "timedOut": False},
        "streams": {"stdout": {"blob": "sha256:x"}, "stderr": {"blob": "sha256:y"}},
    }
    ctx = DigestContext(ws=ws, manifest=manifest, stdout=out, stderr=err)
    if dense:
        ctx.dense = True
    return ctx


def _digest_for(ws, store, text):
    """Store-backed digest of captured real pytest bytes (replayed so blob,
    spans, and retrieval refs are live)."""
    from ctx.digest import render_run_digest
    from ctx.execution import run_capture

    (ws.root / "fixture.txt").write_text(text, encoding="utf-8")
    cap = run_capture(
        ws,
        [sys.executable, "-c", "import sys; sys.stdout.write(open('fixture.txt').read())"],
        store=store,
    )
    return render_run_digest(store, ws, cap.manifest)


# ------------------------------------------------------------------ (a) census
def test_census_lists_all_eight_failures_with_spans(state_home, workspace_dir, real_outputs):
    ws = make_ws(workspace_dir)
    store = make_store(ws)
    digest, m = _digest_for(ws, store, real_outputs["fail_q"])

    # Failure renders are pytest/v2 (the extract/render split); detected
    # from the FAILURES shape, argv is python.
    assert m["digest"]["profile"] == "pytest/v2"
    assert "[pytest/v2 · fail · coverage=8/8]" in digest
    assert "failed 8" in digest and "passed 1" in digest  # bare -q summary parsed exactly
    assert "failing tests (census):" in digest

    rows = CENSUS_ROW_RE.findall(digest)
    assert [r[0] for r in rows] == FAIL_IDS  # all 8, in traceback-block order
    for nodeid, loc, cls, a, b, sid in rows:
        assert re.fullmatch(r"test_seed\.py:\d+", loc)  # file:line location (level 3)
        assert cls.endswith(("Error", "Exception")) or cls != "?"  # failure class (level 3)
        assert int(a) >= 1 and int(b) >= int(a)  # block coordinates, not a bare pointer
        assert sid, f"census row for {nodeid} lacks a span"
    # One-line summaries are DEFAULT in v2 (level 4): the census names the
    # per-test evidence without a retrieval hop.
    assert "beta exploded" in digest
    # First-failure detail still inlined under the default budget, AFTER the census.
    assert "first failure stdout:L" in digest
    assert "    | " in digest
    assert digest.index("failing tests (census):") < digest.index("first failure stdout:L")
    assert "… +" not in digest  # nothing omitted at default budget


def test_census_verbose_mode_output(tmp_path, real_outputs):
    from ctx.digest.pytestprof import PytestProfile

    body = PytestProfile().render(_ctx_for(tmp_path, real_outputs["fail_v"]))
    rows = CENSUS_ROW_RE.findall(body)
    assert [r[0] for r in rows] == FAIL_IDS  # -v shape parses to the same census


# ------------------------------------------------- (b) census outranks detail
def test_census_survives_budget_squeeze_detail_drops(tmp_path, real_outputs):
    from ctx.digest.pytestprof import PytestProfile

    body = PytestProfile().render(
        _ctx_for(tmp_path, real_outputs["fail_q"], result_tokens=400)
    )
    rows = CENSUS_ROW_RE.findall(body)
    assert [r[0] for r in rows] == FAIL_IDS  # full census still rides
    assert "first failure stdout:L" in body  # the pointer survives
    assert "    | " not in body  # the inline detail is what got dropped


# --------------------------------------------------- (c) declared census cap
def test_census_unfittable_escalates_to_flood(tmp_path, real_outputs):
    """v2 semantics (EDC §13): a budget that cannot fit the identity
    census escalates to FLOOD — first-N stable census, exact declared
    omission, and the complete census behind a content-addressed blob —
    instead of v1's identity-dropping '+N more failures' cut."""
    from ctx.digest.pytestprof import PytestProfile

    body = PytestProfile().render(
        _ctx_for(tmp_path, real_outputs["fail_q"], result_tokens=60)
    )
    assert "· flood ·" in body
    assert "failure classes:" in body  # class histogram (census-of-census)
    rows = CENSUS_ROW_RE.findall(body)
    assert 1 <= len(rows) < 8  # capped, never empty
    m = re.search(r"… \+(\d+) more identities · full census blob:([0-9a-f]{12})$", body, re.M)
    assert m, body
    assert len(rows) + int(m.group(1)) == 8  # omission is exact


# ------------------------------------------------------------ (d) dense mode
def test_dense_mode_inlines_per_test_error_lines(tmp_path, real_outputs):
    from ctx.digest.pytestprof import PytestProfile

    plain = PytestProfile().render(_ctx_for(tmp_path, real_outputs["fail_q"]))
    dense = PytestProfile().render(_ctx_for(tmp_path, real_outputs["fail_q"], dense=True))

    # Each census row gains its own assertion/exception evidence line(s).
    assert "ValueError: beta exploded" in dense
    # v2: one-liners are default, so the class-deduped summary rides in the
    # plain census too — but the raw E-line evidence stays dense-only.
    assert "beta exploded" in plain
    assert "ValueError: beta exploded" not in plain
    err_lines = re.findall(r"^\s+E\b.*$", dense, re.M)
    assert len(err_lines) >= 8  # at least one expanded evidence line per row
    # Dense mode stays budget-bounded: unfittable census → declared FLOOD.
    squeezed = PytestProfile().render(
        _ctx_for(tmp_path, real_outputs["fail_q"], result_tokens=60, dense=True)
    )
    assert re.search(r"… \+\d+ more identities", squeezed)


# ------------------------------------------------------- (e) spans resolve
def test_census_spans_resolve_to_traceback_blocks(state_home, workspace_dir, real_outputs):
    from ctx.retrieval import Selector, get

    ws = make_ws(workspace_dir)
    store = make_store(ws)
    digest, m = _digest_for(ws, store, real_outputs["fail_q"])
    short = str(m["id"]).removeprefix("sha256:")[:12]

    row = re.search(
        r"^  \d+\. test_seed\.py::test_gamma  \S+ · \S+ · .*? · "
        r"stdout:L(\d+)-L(\d+) · span ([0-9a-f]{10})$",
        digest, re.M,
    )
    assert row, digest
    a, b, sid = int(row.group(1)), int(row.group(2)), row.group(3)
    span = store.get_span(sid)
    assert span["kind"] == "region" and span["a"] == a and span["b"] == b
    out = get(store, ws, f"run:{short}#stdout", Selector(span=sid))
    assert "test_gamma" in out  # the block's own header
    assert 'assert "needle" in "haystack"' in out  # the actual traceback evidence


# ------------------------------------------- (f) all-pass byte-identical
def test_all_pass_keeps_current_terse_shape(tmp_path, real_outputs):
    """No census scaffolding for green runs: the rendering is byte-identical
    to the pre-census profile (reconstructed here line by line)."""
    from ctx.digest.pytestprof import PytestProfile

    ctx = _ctx_for(tmp_path, real_outputs["pass_default"])
    prof = PytestProfile()
    body = prof.render(ctx)
    expected = "\n".join(
        ctx.header_lines()
        + ["summary:", "  tests: 3 · passed 3"]
        + prof.coverage_lines(ctx, 1)
        + ["next:", "  ctx search run:PENDING 'failed' 'error' --context 3"]
    )
    assert body == expected


# --------------------------------------------- (g) truncated output degrades
def test_truncated_piped_output_degrades_to_partial_census(tmp_path, real_outputs):
    from ctx.digest.pytestprof import PytestProfile

    head = "\n".join(real_outputs["fail_q"].splitlines()[:20]) + "\n"
    prof = PytestProfile()
    ctx = _ctx_for(tmp_path, head, argv=("bash",))  # argv gives no pytest hint
    assert prof.detect(ctx)  # FAILURES section shape still detected
    body = prof.render(ctx)
    assert "summary line not found" in body  # declared degradation, kept
    rows = CENSUS_ROW_RE.findall(body)
    assert rows, body  # census of whatever parsed
    assert rows[0][0] == "TestBox.test_edge"  # header name: no summary section survived
    # v2 honesty: a truncated parse is never attested complete.
    assert "completeness unattested" in body


def test_truncated_verbose_output_uses_progress_rows(tmp_path, real_outputs):
    """-v output cut before the FAILURES section: the census degrades to the
    per-test FAILED progress rows, each with its own line coordinate."""
    from ctx.digest.pytestprof import PytestProfile

    lines = real_outputs["fail_v"].splitlines()
    cut = next(i for i, ln in enumerate(lines) if "FAILURES" in ln)
    head = "\n".join(lines[:cut]) + "\n"
    body = PytestProfile().render(_ctx_for(tmp_path, head))
    rows = CENSUS_ROW_RE.findall(body)
    assert [r[0] for r in rows] == FAIL_IDS  # all 8 from progress rows
    assert all(r[4] == "" for r in rows)  # single-line coordinates, no fake blocks
    assert all(r[2] == "?" for r in rows)  # class honestly unknown, never invented
    assert "summary line not found" in body


# ------------------------------------------------------------ (h) determinism
def test_census_digest_is_deterministic(state_home, workspace_dir, real_outputs):
    ws = make_ws(workspace_dir)
    store = make_store(ws)
    d1, m1 = _digest_for(ws, store, real_outputs["fail_q"])
    d2, m2 = _digest_for(ws, store, real_outputs["fail_q"])
    assert d1 == d2
    assert m1["digest"]["bytesHash"] == m2["digest"]["bytesHash"]


def test_dense_render_is_deterministic(tmp_path, real_outputs):
    from ctx.digest.pytestprof import PytestProfile

    a = PytestProfile().render(_ctx_for(tmp_path, real_outputs["fail_q"], dense=True))
    b = PytestProfile().render(_ctx_for(tmp_path, real_outputs["fail_q"], dense=True))
    assert a == b
