"""The ctx-owned Antigravity SDK environment.

Antigravity is the one supported host whose own CLI cannot be harnessed: `agy`
authenticates by interactive OAuth (so nothing can script it) and its published
hook contract can substitute neither tool input nor tool output, so it has no
output-side gate at any wiring (see :doc:`ADR 005 <../../spec/adr/005-antigravity-hook-contract>`).

The `google-antigravity` **Agent SDK** has neither limitation — it takes a
``GEMINI_API_KEY`` and lets an embedder own the tool implementations, which is
where containment can actually be enforced. But the SDK conflicts with the
system PyJWT, so it can never be a dependency of ``ctx`` itself: it has to run
under a *different* interpreter.

This module owns that interpreter. ``ctx wrap antigravity-sdk`` creates a venv
under the ctx state root, installs the SDK into it, and drops a ``ctx-agy``
launcher next to it; :mod:`ctx.hosts` then detects the launcher and the
orchestrator can route to it like any other harness.

Everything here is fail-open: a missing or half-built environment reports "not
installed" rather than raising, exactly like PATH detection for the other hosts.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

SDK_PACKAGE = "google-antigravity"
LAUNCHER_NAME = "ctx-agy"


def sdk_home() -> Path:
    """The directory ctx owns for the Antigravity SDK environment."""
    from ctx.store import default_state_root

    return default_state_root() / "hosts" / "antigravity-sdk"


def venv_dir() -> Path:
    return sdk_home() / "venv"


def venv_python() -> Path:
    """The interpreter inside the managed venv (may not exist yet)."""
    bin_dir = "Scripts" if os.name == "nt" else "bin"
    exe = "python.exe" if os.name == "nt" else "python"
    return venv_dir() / bin_dir / exe


def launcher_path() -> Path:
    """The `ctx-agy` entry point ctx writes and hosts.py detects."""
    return sdk_home() / "bin" / LAUNCHER_NAME


def shim_source() -> Path:
    """The shim implementation shipped in the repo."""
    return Path(__file__).resolve().parent.parent.parent / "contrib" / "ctx-agy" / "ctx_agy.py"


def sdk_present(python: Path | None = None) -> bool:
    """True when the managed interpreter can actually import the SDK. Checked by
    running it, not by looking for a directory: a venv whose install failed
    half-way is worse than no venv, because it detects as present and then
    fails at launch."""
    py = python or venv_python()
    if not py.is_file():
        return False
    try:
        proc = subprocess.run(
            [str(py), "-c", "import google.antigravity"],
            capture_output=True, text=True, timeout=30,
        )
    except (OSError, subprocess.SubprocessError):
        return False
    return proc.returncode == 0


def is_installed() -> bool:
    """True when both halves exist: the launcher and a working SDK venv."""
    return launcher_path().is_file() and sdk_present()


def _write_launcher() -> Path:
    """Write the `ctx-agy` launcher: a tiny shell script that runs the shipped
    shim under the managed interpreter. Written as a script rather than a
    symlink so the interpreter choice is explicit and greppable."""
    path = launcher_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "#!/usr/bin/env bash\n"
        "# Generated by `ctx wrap antigravity-sdk`. Runs the ctx Antigravity\n"
        "# shim under the interpreter that has the google-antigravity SDK.\n"
        f'exec "{venv_python()}" "{shim_source()}" "$@"\n',
        encoding="utf-8",
    )
    path.chmod(0o755)
    return path


def ensure_venv(*, upgrade: bool = False, quiet: bool = True) -> tuple[bool, str]:
    """Create the managed venv, install the SDK, and write the launcher.

    Idempotent: an existing working environment is left alone unless
    ``upgrade``. Returns ``(ok, message)`` and never raises — a machine without
    network, or with a broken Python, must degrade to "this host is not
    available" rather than breaking `ctx wrap setup` for the other hosts.
    """
    if shim_source().is_file() is False:
        return False, f"shim not found at {shim_source()}"

    py = venv_python()
    if py.is_file() and sdk_present(py) and not upgrade:
        _write_launcher()
        return True, f"already installed: {venv_dir()}"

    try:
        venv_dir().parent.mkdir(parents=True, exist_ok=True)
        if not py.is_file():
            r = subprocess.run(
                [sys.executable, "-m", "venv", str(venv_dir())],
                capture_output=True, text=True, timeout=300,
            )
            if r.returncode != 0:
                return False, f"venv creation failed: {r.stderr.strip()[:200]}"
        args = [str(py), "-m", "pip", "install", "--quiet"]
        if upgrade:
            args.append("--upgrade")
        r = subprocess.run([*args, SDK_PACKAGE], capture_output=True, text=True,
                           timeout=900)
        if r.returncode != 0:
            return False, f"pip install {SDK_PACKAGE} failed: {r.stderr.strip()[:200]}"
    except (OSError, subprocess.SubprocessError) as e:
        return False, f"{type(e).__name__}: {e}"

    if not sdk_present(py):
        return False, f"{SDK_PACKAGE} installed but does not import"
    _write_launcher()
    return True, f"installed {SDK_PACKAGE} into {venv_dir()}"


def remove() -> str:
    """Delete the managed environment (the uninstall path)."""
    import shutil

    home = sdk_home()
    if not home.exists():
        return "nothing to remove"
    shutil.rmtree(home, ignore_errors=True)
    return f"removed {home}"
